# Gthulhu Scheduler Configuration
# This configuration file allows you to adjust scheduler parameters before eBPF program loading

scheduler:
  # Default time slice in nanoseconds (default: 5000000 = 5ms)
  slice_ns_default: 20000000
  
  # Minimum time slice in nanoseconds (default: 500000 = 0.5ms)
  slice_ns_min: 1000000
  # Mode could be: simple, simple-fifo, gthulhu
  mode: gthulhu
# simple_scheduler is only applied if mode = simple
simple_scheduler:
  enable_fifo: true
api:
  url: http://127.0.0.1:8080
  interval: 5
  public_key_path: ./api/config/jwt_public_key.pem
  enabled: true
debug: false
early_processing: false
builtin_idle: false
